### ISSUE TITLE
[issue] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by pasitoapasito** [F5-Refresh/payhere#1]
## 이슈 타입

* [x] 기능추가

## 이슈 내용:

Dockerize를 통한 Django, DRF, MySQL 초기세팅 구성

### version detail
```
Django~=3.2.13
Django-Rest-Framework~=3.13.1
MySQL:5.7
```
develop 브랜치 push

**Comment by KIWONY** [comment]
완료
